### PR TITLE
uprade helm v2 and v3 packages

### LINKED ISSUE #94: Upgrade helm packages for v2 and v3

### PR DESCRIPTION
**Pull request by karuppiah7890**
update test environment setup too accordingly

Fixes #94 #45

### CODE REVIEW

**Comment by karuppiah7890** [comment]
Fixes #45 also. I had to fix the TLS certificate issue. So, I also documented it. I have created the certificates for 10 years though!

**Comment by karuppiah7890** [comment]
Sorry for mixing up and fixing multiple issues in this PR. The issues being

- Upgrade helm v2
- Upgrade helm v3
- Fix TLS certificates
- Document generation of TLS certificates

**Review by jdolitsky — APPROVED** [review]
@karuppiah7890 - ty!

**Comment by karuppiah7890** [comment]
:)

**Pull request merged**
