### PR TITLE
Fix issue 93

### LINKED ISSUE #93: helm push with error when subchart using apiVerion v2
## Summary

Hi !

I got a strange error when I'm using `helm push`

```
$ helm push mychart/ chartmuseum --debug
Error: error unpacking subchart-x.x.x.tgz in mychart: apiVersion 'v2' is not valid. The value must be "v1"

Usage:
  helm push [flags]

Flags:
      --access-token string             Send token in Authorization header [$HELM_REPO_ACCESS_TOKEN]
      --auth-header string              Alternative header to use for token auth [$HELM_REPO_AUTH_HEADER]
...

Error: plugin "push" exited with error
helm.go:94: [debug] plugin "push" exited with error
```

I think maybe can not use `apiVersion: v2` in chart, but I digged into subchart and try to do the same thing using `helm push` to push subchart into chartmuseum like belong:

```
$ helm push subchart/ chartmuseum
```

Nothing error happens ...

I googled a few hours, but can not find related issue.

Hope someone could give me some directions 

## version

helm push version: 
```
$ helm plugin list
NAME       	VERSION	DESCRIPTION                                                                              
push       	0.9.0  	Push chart package to ChartMuseum                                         
```

helm version:
```
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

### PR DESCRIPTION
**Pull request by karuppiah7890**
Fixes #93

### CODE REVIEW

**Comment by karuppiah7890** [comment]
I think we will have to merge #95 first, which has fixed all the TLS certificate issues 😅

**Comment by karuppiah7890** [comment]
In this PR I also temporarily updated helm v2 for the test setup

**Comment by karuppiah7890** [comment]
Ideally it will be removed once we merge #95 . So, this PR is kind of dependent on #95

**Comment by karuppiah7890** [comment]
@jdolitsky Maybe we could add a test for this? In the mock data of the acceptance tests. I didn't think of that and missed it. Mock chart with some mixed API versions

v1 chart > v2 chart > v1 chart
v2 chart > v1 chart > v2 chart

Since helm v2 is still in use by people, maybe it's good to add.

**Comment by karuppiah7890** [comment]
I can create an issue to track it and then add it sometime. Let me know your thoughts

**Comment by karuppiah7890** [comment]
We would have to add appropriate test data. The above is just the first thing that came to my mind

**Comment by jdolitsky** [comment]
@karuppiah7890 - sounds good to me

**Pull request merged**
