### PR TITLE
Add flag to override `appVersion`

### LINKED ISSUE #57: Allow overriding app version during push
Add `--app-version` flag to `helm push` that can override appVersion for a chart.
Analogous to `helm package --version`

### PR DESCRIPTION
**Pull request by vadasambar**
Fixes #57

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]
👍

**Comment by Shukherberg** [comment]
Looks Like --app-version and -a flag doesn't work. 
I tried both variations and has this output:
Error: unknown shorthand flag: 'a' in -a=1.0.0
Or
Error: unknown shorthand flag: 'app-version' in -a=1.0.0

Input: - helm push . --version="1.0.0" -a="1.0.0" chartmuseum

**Comment by vadasambar** [comment]
@Shukherberg , [there hasn't been](https://github.com/chartmuseum/helm-push/releases/tag/v0.9.0) a release since this PR was merged. You should find this flag in the next release.

**Comment by Shukherberg** [comment]
Oh... Thank you for clarifying. Will be waiting till next release then : ) Any upcoming dates?

**Pull request merged**
